org.gradle.jvmargs=-Xmx4096M
org.gradle.daemon = false

# Mc stuff
minecraft_version = 1.21.1
# FIXME: When MC updates, update the FMJ to return min and max version to it. I only made it the one version to avoid confusion.
minecraft_min_version = 1.21.1
minecraft_max_version = 1.21.1
minecraft_supported_versions=1.21.1

# Mod stuff
mod_id = farmersdelight
mod_name = Farmer's Delight
mod_version = 1.21.1-2.4.0
mod_license = MIT License
mod_group_id = vectorwing
mod_authors = MehVahdJukaar, MerchantPug
mod_description = A cozy expansion to farming and cooking!
mod_homepage = https://www.curseforge.com/minecraft/mc-mods/farmers-delight-refabricated
mod_github = https://github.com/MehVahdJukaar/FarmersDelightRefabricated
mod_credits = vectorwing

project_id = 993166
modrinth_project_id = farmers-delight-refabricated

# Loaders
parchment_version = 1.21:2024.07.28

fabric_loader_version = 0.16.9
fabric_api_version = 0.106.0+1.21.1

# Other deps
fabric_asm_version = v2.3
jei_version = 19.9.0.121
rei_version = 16.0.754
emi_version = 1.1.12+1.21
appleskin_version = mc1.21-3.0.4
crafttweaker_version = 21.0.2
crafttweaker_ap_version = 3.0.0.15
port_lib_version = 3.1.0-beta.47.hotfix.2+1.21.1
modmenu_version = 11.0.1

# Follow the README's guide to figure out how to import these.
port_lib_modules = base,config,item_abilities,loot,lazy_registration,recipe_book_categories